# num1 =input("Enter the first number:")
# num2 =input("Enter the second number:")
# result = float(num1) + float(num2)
# print(result)
print()
num1 =input("Enter the the first number:")
num2 =input("Enter the the second number:")
result = float(num1) + float(num2)
print(result)